/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiri.mavenproject1;

import java.time.Duration;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.AbstractTableModel;
import kiri.mavenproject1.entities.RouteStation;

/**
 *
 * @author User
 */
public class routePage extends JDialog {
    
    class RouteTableModel extends AbstractTableModel {
        private List<RouteStation> routeStations;
        private String[] columnNames = new String[] {"Маршрут","Станция","Время стоянки","Время в пути","Расстояние"};
        public RouteTableModel(List<RouteStation> rs) {
            this.routeStations = rs;
        }
        @Override
        public String getColumnName(int columnIndex) {
            return columnNames[columnIndex];
        }
        @Override
        public int getRowCount() {
            return routeStations.size();
        }
        @Override
        public int getColumnCount() {
            return 6;
        }
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            RouteStation current = this.routeStations.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return current.getRoute().toString();
                case 1:
                    return current.getStation().toString();
                case 2:
                    return current.getStayTime().toMinutes()+" минут";
                case 3:
                    return current.getTimeToCome().toMinutes()+"минут";
                case 4:
                    return Float.toString(current.getTotalDistance());
                
            }
            return "nothing";
        }
    }
    /**
     * Creates new form routePage
     */
    public routePage(DBHandle handle, JDialog owner) {
        super(owner, JDialog.ModalityType.DOCUMENT_MODAL);
        initComponents();
        try {
            List<RouteStation> rs = handle.getRouteStations();
            RouteTableModel model = new RouteTableModel(rs);
            this.routeStationsTbl.setModel(model);
            routeStationsTbl.validate();
        }
        catch (Throwable exc) {
            this.messageLbl.setText(exc.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        routeStationsTbl = new javax.swing.JTable();
        messageLbl = new javax.swing.JLabel();

        setTitle("Маршруты");

        routeStationsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(routeStationsTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLbl;
    private javax.swing.JTable routeStationsTbl;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
